/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Entity.ConnexionBdd;
import Entity.FonctionsMetier;
import Entity.Utilisateur;
import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author melvi
 */
public class FrmConnexion extends javax.swing.JFrame {

    FonctionsMetier fm;
    
    public FrmConnexion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMail = new javax.swing.JTextField();
        txtMdp = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        lblErreur = new javax.swing.JLabel();
        lblerreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Connexion");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        jLabel1.setText("Connexion");

        txtMail.setForeground(new java.awt.Color(204, 204, 204));
        txtMail.setText("Adresse Mail");
        txtMail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMailFocusLost(evt);
            }
        });

        txtMdp.setForeground(new java.awt.Color(204, 204, 204));
        txtMdp.setText("Mot de Passe");
        txtMdp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtMdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMdpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMdpFocusLost(evt);
            }
        });

        btnValider.setBackground(new java.awt.Color(0, 0, 0));
        btnValider.setForeground(new java.awt.Color(255, 255, 255));
        btnValider.setText("Valider");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        lblerreur.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMail)
                            .addComponent(txtMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel1)))
                .addContainerGap(147, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(140, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnValider))
                        .addGap(161, 161, 161))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblerreur, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(jLabel1))
                .addGap(31, 31, 31)
                .addComponent(txtMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnValider)
                .addGap(32, 32, 32)
                .addComponent(lblerreur)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErreur)
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        FrmAccueil frm = new FrmAccueil();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
     
        
         if(txtMail.getText().compareTo("") == 0 || txtMail.getText().compareTo("Adresse Mail") == 0 )
        {
            lblerreur.setText("Saisir un login");
        }
        else if(txtMdp.getText().compareTo("") == 0 || txtMail.getText().compareTo("Mot de Passe") == 0)
        {
            lblerreur.setText("Saisir un mot de passe");
        }
        else
        {
            Utilisateur unUser = fm.GetUnUser(txtMail.getText(), txtMdp.getText());
            if(unUser == null)
            {
                lblerreur.setText("Identifiants incorrects");
                
            }
            else
            {
            //Si utilisateur existe
              FrmSommaire frm = new FrmSommaire();
              frm.setVisible(true);
              this.setVisible(false);
            }
        }
        
    }//GEN-LAST:event_btnValiderMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
     
        ConnexionBdd cnx = new ConnexionBdd();
        fm = new FonctionsMetier();
    }//GEN-LAST:event_formWindowOpened

    private void txtMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailFocusGained
           if(txtMail.getText().compareTo("Adresse Mail")==0)
        {
            txtMail.setText("");
            txtMail.setForeground(Color.black);   
            txtMail.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtMail.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtMailFocusGained

    private void txtMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMailFocusLost
          txtMail.setBorder(BorderFactory.createTitledBorder(""));
        if(txtMail.getText().compareTo("")==0)
        {
            txtMail.setText("Adresse Mail");
            txtMail.setForeground(new Color(204,204, 204));
        } 
    }//GEN-LAST:event_txtMailFocusLost

    private void txtMdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMdpFocusGained
           if(txtMdp.getText().compareTo("Mot de Passe")==0)
        {
            txtMdp.setText("");
            txtMdp.setForeground(Color.black);   
            txtMdp.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtMdp.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtMdpFocusGained

    private void txtMdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMdpFocusLost
           txtMdp.setBorder(BorderFactory.createTitledBorder(""));
        if(txtMdp.getText().compareTo("")==0)
        {
            txtMdp.setText("Mot de Passe");
            txtMdp.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtMdpFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmConnexion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmConnexion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnValider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErreur;
    private javax.swing.JLabel lblerreur;
    private javax.swing.JTextField txtMail;
    private javax.swing.JTextField txtMdp;
    // End of variables declaration//GEN-END:variables
}
