/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Entity.ConnexionBdd;
import Entity.FonctionsMetier;
import Entity.Medicament;
import Model.ModelMedicament;
import Model.ModelTypeExistant;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author noasillam
 */
public class FrmInsererValeurMedicament extends javax.swing.JFrame {

    /**
     * Creates new form FrmListerMedicament
     */
    
    FonctionsMetier fm;
    ModelTypeExistant mdlTypeMedicament;
    ModelMedicament mdlMedicament;
    Medicament leMedicament;
    FonctionsMetier fm1;
    public FrmInsererValeurMedicament() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        tblComposantRestant = new javax.swing.JTable();
        nomMedicament = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblTypeExistant = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListeMedicaments = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListeTypePossible = new javax.swing.JTable();
        btnAjouter = new javax.swing.JButton();
        txtTypeAjouter1 = new javax.swing.JTextField();
        txtTypeAjouter = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        tblComposantRestant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblComposantRestant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComposantRestantMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblComposantRestant);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        tblTypeExistant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblTypeExistant.setEnabled(false);
        tblTypeExistant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTypeExistantMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblTypeExistant);

        jLabel1.setText(" Formes des médicaments déjà existant");

        tblListeMedicaments.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListeMedicaments.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListeMedicamentsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblListeMedicaments);

        tblListeTypePossible.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblListeTypePossible.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListeTypePossibleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblListeTypePossible);

        btnAjouter.setText("ajouter");
        btnAjouter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAjouterMouseClicked(evt);
            }
        });

        txtTypeAjouter1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeAjouter1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID médicament");

        jLabel3.setText("ID type médicament");

        jLabel4.setText("Liste des Médicaments");

        jLabel5.setText("Les différentes forme(s) ajoutable(s) au médicament");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addComponent(nomMedicament))
                            .addComponent(btnBack))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel4))
                            .addComponent(jLabel5))
                        .addGap(192, 192, 192)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAjouter)
                                    .addComponent(jLabel1))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtTypeAjouter1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTypeAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomMedicament)
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTypeAjouter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTypeAjouter1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addComponent(btnAjouter)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        
         fm = new FonctionsMetier();
        FrmMedicament frm = new FrmMedicament();
        frm.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_btnBackMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConnexionBdd bdd = new ConnexionBdd(); 
        fm = new FonctionsMetier();
        mdlMedicament = new ModelMedicament();
        mdlMedicament.loadDatas(fm.GetAllMedicaments());
        tblListeMedicaments.setModel(mdlMedicament);
      
      
    }//GEN-LAST:event_formWindowOpened

    private void tblComposantRestantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComposantRestantMouseClicked
        tblComposantRestant.getValueAt(tblComposantRestant.getSelectedRow(), 0).toString();
      //  txtDepotLegal.setText(tblComposantRestant.getValueAt(tblComposantRestant.getSelectedRow(), 2).toString());
    }//GEN-LAST:event_tblComposantRestantMouseClicked

    private void tblTypeExistantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTypeExistantMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblTypeExistantMouseClicked

    private void tblListeMedicamentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListeMedicamentsMouseClicked
         ConnexionBdd bdd = new ConnexionBdd(); 
        fm = new FonctionsMetier();
        
        mdlTypeMedicament = new ModelTypeExistant();
        mdlTypeMedicament.loadDatas(fm.GetAllTypeMedicament(Integer.parseInt(tblListeMedicaments.getValueAt(tblListeMedicaments.getSelectedRow(), 2).toString())));
        tblTypeExistant.setModel(mdlTypeMedicament);
        
        mdlTypeMedicament = new ModelTypeExistant();
        mdlTypeMedicament.loadDatas(fm.GetAllTypePasMedicament(Integer.parseInt(tblListeMedicaments.getValueAt(tblListeMedicaments.getSelectedRow(), 2).toString())));
        tblListeTypePossible.setModel(mdlTypeMedicament);
    
    }//GEN-LAST:event_tblListeMedicamentsMouseClicked

    private void tblListeTypePossibleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListeTypePossibleMouseClicked

       
        txtTypeAjouter.setText(tblListeTypePossible.getValueAt(tblListeTypePossible.getSelectedRow(), 0).toString());
        txtTypeAjouter1.setText(tblListeMedicaments.getValueAt(tblListeMedicaments.getSelectedRow(), 2).toString());


    }//GEN-LAST:event_tblListeTypePossibleMouseClicked

    private void btnAjouterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAjouterMouseClicked


       fm.insertTypeMedicament(Integer.parseInt(txtTypeAjouter.getText()),Integer.parseInt(txtTypeAjouter1.getText()));
mdlTypeMedicament = new ModelTypeExistant();
        mdlTypeMedicament.loadDatas(fm.GetAllTypeMedicament(Integer.parseInt(tblListeMedicaments.getValueAt(tblListeMedicaments.getSelectedRow(), 2).toString())));
        tblTypeExistant.setModel(mdlTypeMedicament);
        
        mdlTypeMedicament = new ModelTypeExistant();
        mdlTypeMedicament.loadDatas(fm.GetAllTypePasMedicament(Integer.parseInt(tblListeMedicaments.getValueAt(tblListeMedicaments.getSelectedRow(), 2).toString())));
        tblListeTypePossible.setModel(mdlTypeMedicament);
//       

    }//GEN-LAST:event_btnAjouterMouseClicked

    private void txtTypeAjouter1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeAjouter1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeAjouter1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmInsererValeurMedicament().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAjouter;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel nomMedicament;
    private javax.swing.JTable tblComposantRestant;
    private javax.swing.JTable tblListeMedicaments;
    private javax.swing.JTable tblListeTypePossible;
    private javax.swing.JTable tblTypeExistant;
    private javax.swing.JTextField txtTypeAjouter;
    private javax.swing.JTextField txtTypeAjouter1;
    // End of variables declaration//GEN-END:variables
}
