/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Entity.ConnexionBdd;
import Entity.FonctionsMetier;
import Entity.Utilisateur;
import static Vue.FrmAccueil.frm;
import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JTextField;
import javax.swing.border.Border;
import javax.swing.border.TitledBorder;

/**
 *
 * @author melvi
 */
public class FrmInscription extends javax.swing.JFrame {

   FonctionsMetier fm;
   
   
    public FrmInscription() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        rHomme = new javax.swing.JRadioButton();
        rFemme = new javax.swing.JRadioButton();
        txtNom = new javax.swing.JTextField();
        txtPrenom = new javax.swing.JTextField();
        txtAdresse = new javax.swing.JTextField();
        txtCodePostal = new javax.swing.JTextField();
        txtVille = new javax.swing.JTextField();
        txtTelephone = new javax.swing.JTextField();
        txtAdresseMail = new javax.swing.JTextField();
        txtMdp = new javax.swing.JTextField();
        txtConfirmerMdp = new javax.swing.JTextField();
        btnValider = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblErreur = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inscription");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        buttonGroup1.add(rHomme);
        rHomme.setText("Mr");

        buttonGroup1.add(rFemme);
        rFemme.setText("Mme");

        txtNom.setForeground(new java.awt.Color(204, 204, 204));
        txtNom.setText("Nom");
        txtNom.setToolTipText("");
        txtNom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomFocusLost(evt);
            }
        });

        txtPrenom.setForeground(new java.awt.Color(204, 204, 204));
        txtPrenom.setText("Prenom");
        txtPrenom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtPrenom.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrenomFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrenomFocusLost(evt);
            }
        });

        txtAdresse.setForeground(new java.awt.Color(204, 204, 204));
        txtAdresse.setText("Adresse");
        txtAdresse.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtAdresse.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAdresseFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdresseFocusLost(evt);
            }
        });

        txtCodePostal.setForeground(new java.awt.Color(204, 204, 204));
        txtCodePostal.setText("Code Postal");
        txtCodePostal.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtCodePostal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCodePostalFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCodePostalFocusLost(evt);
            }
        });

        txtVille.setForeground(new java.awt.Color(204, 204, 204));
        txtVille.setText("Ville");
        txtVille.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtVille.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtVilleFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtVilleFocusLost(evt);
            }
        });

        txtTelephone.setForeground(new java.awt.Color(204, 204, 204));
        txtTelephone.setText("Téléphone");
        txtTelephone.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtTelephone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTelephoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTelephoneFocusLost(evt);
            }
        });

        txtAdresseMail.setForeground(new java.awt.Color(204, 204, 204));
        txtAdresseMail.setText("Adresse mail");
        txtAdresseMail.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtAdresseMail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAdresseMailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAdresseMailFocusLost(evt);
            }
        });

        txtMdp.setForeground(new java.awt.Color(204, 204, 204));
        txtMdp.setText("Mot de Passe");
        txtMdp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtMdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtMdpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMdpFocusLost(evt);
            }
        });

        txtConfirmerMdp.setForeground(new java.awt.Color(204, 204, 204));
        txtConfirmerMdp.setText("Confirmer Mot de Passe");
        txtConfirmerMdp.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtConfirmerMdp.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtConfirmerMdpFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtConfirmerMdpFocusLost(evt);
            }
        });

        btnValider.setBackground(new java.awt.Color(0, 0, 0));
        btnValider.setForeground(new java.awt.Color(255, 255, 255));
        btnValider.setText("Valider");
        btnValider.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnValiderMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Inscription");

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        lblErreur.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblErreur.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnValider))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btnBack)
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(txtNom, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(txtPrenom, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtAdresse)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodePostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtVille, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtMdp)
                                    .addComponent(txtAdresseMail)
                                    .addComponent(txtTelephone)
                                    .addComponent(txtConfirmerMdp, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                    .addComponent(lblErreur, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rHomme, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rFemme, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rHomme)
                    .addComponent(rFemme))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPrenom, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtNom))
                .addGap(18, 18, 18)
                .addComponent(txtAdresse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtCodePostal, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(txtVille))
                .addGap(18, 18, 18)
                .addComponent(txtTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtAdresseMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtConfirmerMdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnValider)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErreur)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
      FrmAccueil frm = new FrmAccueil();
                    frm.setVisible(true);
                this.setVisible(false);
                    
    }//GEN-LAST:event_btnBackMouseClicked

    private void txtNomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusGained
        
        if(txtNom.getText().compareTo("Nom")==0)
        {
            txtNom.setText("");
            txtNom.setForeground(Color.black);      
            txtNom.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtNom.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtNomFocusGained

    private void txtNomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomFocusLost
       txtNom.setBorder(BorderFactory.createTitledBorder(""));
        if(txtNom.getText().compareTo("")==0)
        {
            txtNom.setText("Nom");
            txtNom.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtNomFocusLost

    private void txtPrenomFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrenomFocusGained
        if(txtPrenom.getText().compareTo("Prenom")==0)
        {
            txtPrenom.setText("");
            txtPrenom.setForeground(Color.black);   
            txtPrenom.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtPrenom.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtPrenomFocusGained

    private void txtPrenomFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrenomFocusLost
        txtPrenom.setBorder(BorderFactory.createTitledBorder("")); 
        
        if(txtPrenom.getText().compareTo("")==0)
        {
            txtPrenom.setText("Prenom");
            txtPrenom.setForeground(new Color(204,204, 204));
           
        }
    }//GEN-LAST:event_txtPrenomFocusLost

    private void txtAdresseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresseFocusGained
          if(txtAdresse.getText().compareTo("Adresse")==0)
        {
            txtAdresse.setText("");
            txtAdresse.setForeground(Color.black);   
            txtAdresse.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtAdresse.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtAdresseFocusGained

    private void txtAdresseFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresseFocusLost
        txtAdresse.setBorder(BorderFactory.createTitledBorder(""));       
        if(txtAdresse.getText().compareTo("")==0)
        {
            txtAdresse.setText("Adresse");
            txtAdresse.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtAdresseFocusLost

    private void txtCodePostalFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodePostalFocusGained
             if(txtCodePostal.getText().compareTo("Code Postal")==0)
        {
            txtCodePostal.setText("");
            txtCodePostal.setForeground(Color.black);   
            txtCodePostal.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtCodePostal.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtCodePostalFocusGained

    private void txtCodePostalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCodePostalFocusLost
        txtCodePostal.setBorder(BorderFactory.createTitledBorder(""));
        if(txtCodePostal.getText().compareTo("")==0)
        {
            txtCodePostal.setText("Code Postal");
            txtCodePostal.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtCodePostalFocusLost

    private void txtVilleFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVilleFocusGained
               if(txtVille.getText().compareTo("Ville")==0)
        {
            txtVille.setText("");
            txtVille.setForeground(Color.black);   
            txtVille.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtVille.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtVilleFocusGained

    private void txtVilleFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtVilleFocusLost
        txtVille.setBorder(BorderFactory.createTitledBorder(""));
        if(txtVille.getText().compareTo("")==0)
        {
            txtVille.setText("Ville");
            txtVille.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtVilleFocusLost

    private void txtTelephoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneFocusGained
         if(txtTelephone.getText().compareTo("Téléphone")==0)
        {
            txtTelephone.setText("");
            txtTelephone.setForeground(Color.black);   
            txtTelephone.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtTelephone.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtTelephoneFocusGained

    private void txtTelephoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTelephoneFocusLost
         txtTelephone.setBorder(BorderFactory.createTitledBorder(""));
        if(txtTelephone.getText().compareTo("")==0)
        {
            txtTelephone.setText("Téléphone");
            txtTelephone.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtTelephoneFocusLost

    private void txtAdresseMailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresseMailFocusGained
           if(txtAdresseMail.getText().compareTo("Adresse mail")==0)
        {
            txtAdresseMail.setText("");
            txtAdresseMail.setForeground(Color.black);   
            txtAdresseMail.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtAdresseMail.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtAdresseMailFocusGained

    private void txtAdresseMailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAdresseMailFocusLost
          txtAdresseMail.setBorder(BorderFactory.createTitledBorder(""));
        if(txtAdresseMail.getText().compareTo("")==0)
        {
            txtAdresseMail.setText("Adresse mail");
            txtAdresseMail.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtAdresseMailFocusLost

    private void txtMdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMdpFocusGained
             if(txtMdp.getText().compareTo("Mot de Passe")==0)
        {
            txtMdp.setText("");
            txtMdp.setForeground(Color.black);   
            txtMdp.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtMdp.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtMdpFocusGained

    private void txtMdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMdpFocusLost
     
        
        txtMdp.setBorder(BorderFactory.createTitledBorder(""));
        if(txtMdp.getText().compareTo("")==0)
        {
            txtMdp.setText("Mot de Passe");
            txtMdp.setForeground(new Color(204,204, 204));
        }
    }//GEN-LAST:event_txtMdpFocusLost

    private void txtConfirmerMdpFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmerMdpFocusGained
         if(txtConfirmerMdp.getText().compareTo("Confirmer Mot de Passe")==0)
        {
            txtConfirmerMdp.setText("");
            txtConfirmerMdp.setForeground(Color.black);   
            txtConfirmerMdp.setBorder(BorderFactory.createMatteBorder(2,2,2,2, Color.black));
            txtConfirmerMdp.setBackground(Color.white);
          }
    }//GEN-LAST:event_txtConfirmerMdpFocusGained

    private void txtConfirmerMdpFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtConfirmerMdpFocusLost
          txtConfirmerMdp.setBorder(BorderFactory.createTitledBorder(""));
        if(txtConfirmerMdp.getText().compareTo("")==0)
        {
            txtConfirmerMdp.setText("Confirmer Mot de Passe");
           txtConfirmerMdp.setForeground(new Color(204,204, 204));
    
        }
    }//GEN-LAST:event_txtConfirmerMdpFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ConnexionBdd cnx = new ConnexionBdd();
        fm = new FonctionsMetier();

    }//GEN-LAST:event_formWindowOpened

    private void btnValiderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnValiderMouseClicked
     
            
           if(rHomme.isSelected() == false && rFemme.isSelected() == false )
        {
            lblErreur.setText("Saisir un sexe");
        }
           
       else if(txtNom.getText().compareTo("") == 0 || txtNom.getText().compareTo("Nom") == 0)
        {
            lblErreur.setText("Saisir un Nom");
            txtNom.setBackground(Color.red);

        }
        else if(txtPrenom.getText().compareTo("") == 0 || txtPrenom.getText().compareTo("Prenom") == 0 )
        {
            lblErreur.setText("Saisir un Prenom");
            txtPrenom.setBackground(Color.red);
        }
            
              else if(txtAdresse.getText().compareTo("") == 0 || txtAdresse.getText().compareTo("Adresse") == 0 )
        {
            lblErreur.setText("Saisir un Adresse");
            txtAdresse.setBackground(Color.red);
        }
            
              else if(txtCodePostal.getText().compareTo("") == 0 || txtCodePostal.getText().compareTo("Code Postal") == 0 )
        {
            lblErreur.setText("Saisir un code postal");
            txtCodePostal.setBackground(Color.red);
        }
            
              else if(txtVille.getText().compareTo("") == 0 || txtVille.getText().compareTo("Ville") == 0 )
        {
            lblErreur.setText("Saisir une ville");
            txtVille.setBackground(Color.red);
        }
            
              else if(txtTelephone.getText().compareTo("") == 0 || txtTelephone.getText().compareTo("Téléphone") == 0 )
        {
            lblErreur.setText("Saisir un numéro de téléphone");
           txtTelephone.setBackground(Color.red);
        }
            
              else if(txtAdresseMail.getText().compareTo("") == 0 || txtAdresseMail.getText().compareTo("Adresse mail") == 0 )
        {
            lblErreur.setText("Saisir une adresse mail valide");
           txtAdresseMail.setBackground(Color.red);
        }
            
              else if(txtMdp.getText().compareTo("") == 0 || txtMdp.getText().compareTo("Mot de Passe") == 0 )
        {
            lblErreur.setText("Saisir un mot de passe");
            txtMdp.setBackground(Color.red);
        }
            
              else if(txtConfirmerMdp.getText().compareTo(txtMdp.getText()) != 0 )
        {
            lblErreur.setText("Le mot de passe est différent !");
           txtConfirmerMdp.setBackground(Color.red);
        }
           
            
        else
        {
            String sexe = "Femme";
            if(rHomme.isSelected() == true)
            {
                sexe = "Homme";
            }
             //Inscription validé   
//            Utilisateur unUser = fm.createUnUser(txtNom.getText(), txtPrenom.getText(),buttonGroup1.getSelection().toString(),txtAdresse.getText(),Integer.parseInt(txtCodePostal.getText()), txtVille.getText(), Integer.parseInt(txtTelephone.getText()), txtAdresseMail.getText(), txtMdp.getText());
fm.createUnUser(txtNom.getText(), txtPrenom.getText(),sexe,txtAdresse.getText(),Integer.parseInt(txtCodePostal.getText()), txtVille.getText(), Integer.parseInt(txtTelephone.getText()), txtAdresseMail.getText(), txtMdp.getText());
            
                 FrmConnexion frm = new FrmConnexion();
                 frm.setVisible(true);
                this.setVisible(false);
          
        }
        
        
    }//GEN-LAST:event_btnValiderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             new FrmInscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnValider;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblErreur;
    private javax.swing.JRadioButton rFemme;
    private javax.swing.JRadioButton rHomme;
    private javax.swing.JTextField txtAdresse;
    private javax.swing.JTextField txtAdresseMail;
    private javax.swing.JTextField txtCodePostal;
    private javax.swing.JTextField txtConfirmerMdp;
    private javax.swing.JTextField txtMdp;
    private javax.swing.JTextField txtNom;
    private javax.swing.JTextField txtPrenom;
    private javax.swing.JTextField txtTelephone;
    private javax.swing.JTextField txtVille;
    // End of variables declaration//GEN-END:variables
}
