/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vue;

import Entity.Composant;
import Entity.ConnexionBdd;
import Entity.FonctionsMetier;
import java.util.HashSet;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.data.statistics.HistogramDataset;
import org.jfree.data.statistics.HistogramType;

/**
 *
 * @author melvi
 */
public class FrmGraphiqueQuantite extends javax.swing.JFrame {

    FonctionsMetier fm;
    ConnexionBdd cnx;    
    static FrmGraphiqueQuantite frm =  new FrmGraphiqueQuantite();

    
    public FrmGraphiqueQuantite() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboMeds = new javax.swing.JComboBox<>();
        btnGraph1 = new javax.swing.JButton();
        btnGraph2 = new javax.swing.JButton();
        btnGraph3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GraphiqueQuantite");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        btnGraph1.setText("Graphique n°1");
        btnGraph1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraph1MouseClicked(evt);
            }
        });

        btnGraph2.setText("Graphique n°2");
        btnGraph2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraph2MouseClicked(evt);
            }
        });

        btnGraph3.setText("Graphique n°3");
        btnGraph3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnGraph3MouseClicked(evt);
            }
        });

        jLabel1.setText("Statistiques");

        btnBack.setText("Back");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnBack)
                .addGap(77, 77, 77)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnGraph3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                    .addComponent(btnGraph2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGraph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(cboMeds, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGraph1)
                    .addComponent(cboMeds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnGraph2)
                .addGap(18, 18, 18)
                .addComponent(btnGraph3)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
    
      // Accès à la BDD
        cnx = new ConnexionBdd();
        fm = new FonctionsMetier();
        for(String m  : fm.GetAllMedicamentsNom())
        {
            cboMeds.addItem(m);
        }
        
       /* for(String composant : fm.GetAllComposantRestant("e"))
        {
            cboActions.addItem(composant);
        }*/
    }//GEN-LAST:event_formWindowOpened

    private void btnGraph1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraph1MouseClicked
        cnx = new ConnexionBdd();
       // CAMENBERT
        DefaultPieDataset donnees = new DefaultPieDataset();
        
        for (Map.Entry valeur : fm.GetDatasGraphique1(cboMeds.getSelectedItem().toString()).entrySet())
        {
            donnees.setValue(valeur.getKey().toString(), Double.parseDouble(valeur.getValue().toString()));
            //recupere valeur de la requete
        }
       
        JFreeChart chart2 = ChartFactory.createPieChart("Nombre de composants pour un médicament "+cboMeds.getSelectedItem().toString(), donnees, true, false, Locale.CANADA);
        ChartFrame fra = new ChartFrame("Graphique n°1", chart2);
        fra.pack();
        fra.setVisible(true);
    }//GEN-LAST:event_btnGraph1MouseClicked

    private void btnGraph2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraph2MouseClicked
        // TODO add your handling code here:
        
        DefaultCategoryDataset donnees = new DefaultCategoryDataset();
        
        for (Map.Entry valeur : fm.GetDatasGraphique2().entrySet())
        {
            donnees.setValue(Double.parseDouble(valeur.getValue().toString()),  "dede",String.valueOf(valeur.getKey()));
            //donnees.setValue(valeur.getKey().toString(), Double.parseDouble(valeur.getValue().toString()));
            //recupere valeur de la requete
        }
        
        JFreeChart chart1 = ChartFactory.createLineChart("Présentation des médicaments ", "Nom des présentations", null, donnees, PlotOrientation.VERTICAL, false, true, true);
       //JFreeChart chart1 = ChartFactory.createLineChart("Presentation des medicament ", PlotOrientation.VERTICAL, , null, donnees);
        ChartFrame fra = new ChartFrame("Graphique n°2", chart1);
        
        
        fra.pack();
        fra.setVisible(true);
        
    }//GEN-LAST:event_btnGraph2MouseClicked

    private void btnGraph3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGraph3MouseClicked
        DefaultCategoryDataset donnees = new DefaultCategoryDataset();
        
        
        String xAxisLabel = "Sexe";
        String yAxis = "Nombre";
        PlotOrientation orientation = PlotOrientation.VERTICAL;
        
        
        
        for (Map.Entry valeur : fm.GetDatasGraphique3().entrySet())
        {
           donnees.setValue(Double.parseDouble(valeur.getValue().toString()), valeur.getKey().toString(), "");
        }
        
        
        boolean show = true;
        boolean toolTips = false;
        boolean urls = false;
        JFreeChart chart = ChartFactory.createBarChart("Nombre de personnes par sexe", xAxisLabel, yAxis,
                donnees, orientation, show, toolTips, urls);
        
        ChartFrame fra = new ChartFrame("Graphique n°3", chart);
        fra.pack();
        fra.setVisible(true);
    }//GEN-LAST:event_btnGraph3MouseClicked

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        
         FrmSommaire frm = new FrmSommaire();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBackMouseClicked

 
    public static void main(String args[]) {


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             FrmGraphiqueQuantite frm =  new FrmGraphiqueQuantite();
                      frm.setVisible(true);
             
   

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGraph1;
    private javax.swing.JButton btnGraph2;
    private javax.swing.JButton btnGraph3;
    private javax.swing.JComboBox<String> cboMeds;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
